### ISSUE TITLE
[JENKINS-67434] intermittent unstable connection between agent to master 

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/remoting#1456]
<p>Our application team trying to make a connection from their agents to Jenkins master. The initial connectivity was good and after an amount of time, we see a disruption. </p>

<p>The build nodes succeeded to be connected to the Jenkins master, but sometimes the Jenkins master does not reply back (showing timeout). We are using WebSocket method.</p>

<p> </p>

<p>Jenkins version: 2.319.1 (LTS)</p>

<p>Launch method: Launch agent by connecting it to the controller.</p>

<p>Agent name: HSM - Pipe Plaza</p>

<p>Agent version: 4.11.2</p>

<p>JDK version: 1.8</p>

<p>Agent logs: Refer to the attachment</p>

<p>Jenkins Master logs: Refer to the attachment. </p>

<p> </p>

<p>2021-12-21 04:20:34.830+0000 <span class="error">&#91;id=181293&#93;</span> INFO j.s.DefaultJnlpSlaveReceiver#channelClosed: Jetty (winstone)-181293 for HSM - Dry Dry Desert terminated: java.nio.channels.ClosedChannelException</p>

<p> </p>

<p>While agent connection we can see below Warning in the logs. May I know what this warning refers.</p>

<p>2021-12-21 04:25:21.601+0000 <span class="error">&#91;id=181571&#93;</span> WARNING hudson.model.Slave#reportLauncherCreateError: Issue with creating launcher for agent HSM - Grumble Volcano. The agent has not been fully initialized yetProbably there is a race condition with Agent reconnection or disconnection, check other log entries<br/>
 java.lang.IllegalStateException: No remoting channel to the agent OR it has not been fully initialized yet<br/>
 at hudson.model.Slave.reportLauncherCreateError(Slave.java:540)<br/>
 at hudson.model.Slave.createLauncher(Slave.java:512)<br/>
 at org.jenkinsci.plugins.workflow.support.DefaultStepContext.makeLauncher(DefaultStepContext.java:160)<br/>
 at org.jenkinsci.plugins.workflow.support.DefaultStepContext.get(DefaultStepContext.java:83)<br/>
 at org.jenkinsci.plugins.docker.workflow.WithContainerStep$Callback.finished(WithContainerStep.java:391)<br/>
 at org.jenkinsci.plugins.workflow.steps.BodyExecutionCallback$TailCall.onFailure(BodyExecutionCallback.java:128)<br/>
 at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution$FailureAdapter.receive(CpsBodyExecution.java:361)<br/>
 at com.cloudbees.groovy.cps.impl.ThrowBlock$1.receive(ThrowBlock.java:68)<br/>
 at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)<br/>
 at com.cloudbees.groovy.cps.Next.step(Next.java:83)<br/>
 at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)<br/>
 at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)<br/>
 at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)<br/>
 at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)<br/>
 at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)<br/>
 at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)<br/>
 at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)<br/>
 at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:185)<br/>
 at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:402)<br/>
 at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:96)<br/>
 at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:314)<br/>
 at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:278)<br/>
 at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)<br/>
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)<br/>
 at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)<br/>
 at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)<br/>
 at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)<br/>
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)<br/>
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)<br/>
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)<br/>
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)<br/>
 at java.lang.Thread.run(Thread.java:748)</p>

<p> </p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=wri1kor">wri1kor</a>, imported from: <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-67434" target="_blank">intermittent unstable connection between agent to master </a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Critical
<li><b>component(s)</b>: remoting
<li><b>label(s)</b>: jenkins, websocket
<li><b>resolution</b>: Unresolved
<li><b>votes</b>: 1
<li><b>watchers</b>: 5
<li><b>imported</b>: 2025-11-25
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>Our application team trying to make a connection from their agents to Jenkins master. The initial connectivity was good and after an amount of time, we see a disruption. </p>

<p>The build nodes succeeded to be connected to the Jenkins master, but sometimes the Jenkins master does not reply back (showing timeout). We are using WebSocket method.</p>

<p> </p>

<p>Jenkins version: 2.319.1 (LTS)</p>

<p>Launch method: Launch agent by connecting it to the controller.</p>

<p>Agent name: HSM - Pipe Plaza</p>

<p>Agent version: 4.11.2</p>

<p>JDK version: 1.8</p>

<p>Agent logs: Refer to the attachment</p>

<p>Jenkins Master logs: Refer to the attachment. </p>

<p> </p>

<p>2021-12-21 04:20:34.830+0000 <span class="error">&#91;id=181293&#93;</span> INFO j.s.DefaultJnlpSlaveReceiver#channelClosed: Jetty (winstone)-181293 for HSM - Dry Dry Desert terminated: java.nio.channels.ClosedChannelException</p>

<p> </p>

<p>While agent connection we can see below Warning in the logs. May I know what this warning refers.</p>

<p>2021-12-21 04:25:21.601+0000 <span class="error">&#91;id=181571&#93;</span> WARNING hudson.model.Slave#reportLauncherCreateError: Issue with creating launcher for agent HSM - Grumble Volcano. The agent has not been fully initialized yetProbably there is a race condition with Agent reconnection or disconnection, check other log entries
 java.lang.IllegalStateException: No remoting channel to the agent OR it has not been fully initialized yet
 at hudson.model.Slave.reportLauncherCreateError(Slave.java:540)
 at hudson.model.Slave.createLauncher(Slave.java:512)
 at org.jenkinsci.plugins.workflow.support.DefaultStepContext.makeLauncher(DefaultStepContext.java:160)
 at org.jenkinsci.plugins.workflow.support.DefaultStepContext.get(DefaultStepContext.java:83)
 at org.jenkinsci.plugins.docker.workflow.WithContainerStep$Callback.finished(WithContainerStep.java:391)
 at org.jenkinsci.plugins.workflow.steps.BodyExecutionCallback$TailCall.onFailure(BodyExecutionCallback.java:128)
 at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution$FailureAdapter.receive(CpsBodyExecution.java:361)
 at com.cloudbees.groovy.cps.impl.ThrowBlock$1.receive(ThrowBlock.java:68)
 at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
 at com.cloudbees.groovy.cps.Next.step(Next.java:83)
 at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
 at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
 at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
 at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
 at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
 at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
 at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
 at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:185)
 at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:402)
 at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:96)
 at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:314)
 at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:278)
 at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
 at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
 at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:748)</p>

<p> </p></pre>
</details>
</details>
<ul><li><i>environment</i>: <code>Prod</code></li></ul>
<details><summary><i>3 attachments</i></summary>

- [agent_logs](https://issues.jenkins.io/secure/attachment/56986/agent_logs)
- [jenkins.log-20211221.gz](https://issues.jenkins.io/secure/attachment/56987/jenkins.log-20211221.gz)
- [screenshot.PNG](https://issues.jenkins.io/secure/attachment/56985/screenshot.PNG)
  > ![screenshot.PNG](https://issues.jenkins.io/secure/attachment/56985/screenshot.PNG)
</details>

**Comment by jtnord** [comment]
are you by any chance going through a reverse proxy / firewall to reach Jenkins from the Agent?  Many firewalls will just kill HTTP (including web socket) connections after some max length of time open, or when reloading their configuration.
Additionally some have the idle connection timeout to less that the websocket ping keep-alive ping interval.  
The code has changed in the last 3 years, please recreate a new issue with up to date stack traces and details of network infrastructure if this is still happening
