### ISSUE TITLE
[JENKINS-3019] Failure building on slave due to network communication should not be marked as failed

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/remoting#928]
<p>Occasionally something happens (network failure, someone shuts down the machine, <br/>
etc.) which makes a slave build fail.  In this situation, currently Hudson gives <br/>
an exception like this:</p>

<p>hudson.util.IOException2: Failed to join the process<br/>
	at hudson.Proc$RemoteProc.join(Proc.java:231)<br/>
	at hudson.tasks.Ant.perform(Ant.java:180)<br/>
	at hudson.model.Build$RunnerImpl.build(Build.java:138)<br/>
	at hudson.model.Build$RunnerImpl.doRun(Build.java:113)<br/>
	at hudson.model.AbstractBuild$AbstractRunner.run(AbstractBuild.java:244)<br/>
	at hudson.model.Run.run(Run.java:842)<br/>
	at hudson.model.Build.run(Build.java:88)<br/>
	at hudson.model.ResourceController.execute(ResourceController.java:70)<br/>
	at hudson.model.Executor.run(Executor.java:90)<br/>
Caused by: java.util.concurrent.ExecutionException: <br/>
hudson.remoting.RequestAbortedException: java.net.SocketException: Connection <br/>
reset<br/>
	at hudson.remoting.Request$1.get(Request.java:165)<br/>
	at hudson.remoting.Request$1.get(Request.java:134)<br/>
	at hudson.remoting.FutureAdapter.get(FutureAdapter.java:32)<br/>
	at hudson.Proc$RemoteProc.join(Proc.java:223)<br/>
	... 8 more</p>

<p>This in itself is fine, but it then in turn marks the build as failed.  This <br/>
results in Hudson thinking the changes which occurred for this build were the <br/>
cause for the build.</p>

<p>This causes two problems:</p>

<p>  1. When the build is re-run and then works, Hudson won't list the changes <br/>
which occurred before the broken build as being changes which belong to the new <br/>
build.</p>

<p>  2. If you are running the CI Game plugin, the unlucky soul who committed the <br/>
changes immediately before Hudson broke gets -10.0 points.  IMO in this <br/>
situation the points should be docked against Hudson itself, or some other <br/>
equivalent placeholder player...</p>

<p>On a larger scale, <b>any</b> build which fails due to Hudson itself should not be <br/>
marked as failed for the same reason; this just happens to be the most common <br/>
situation which we encounter in practice.</p>

---
<details><summary><i>Originally reported by <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/trejkaz.jpg" title="trejkaz's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=trejkaz">trejkaz</a>, imported from: <a class="no-jira-link-rewrite" href="https://issues.jenkins.io/browse/JENKINS-3019" target="_blank">Failure building on slave due to network communication should not be marked as failed</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Major
<li><b>component(s)</b>: remoting
<li><b>resolution</b>: Unresolved
<li><b>votes</b>: 1
<li><b>watchers</b>: 1
<li><b>imported</b>: 2025-11-25
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>Occasionally something happens (network failure, someone shuts down the machine, 
etc.) which makes a slave build fail.  In this situation, currently Hudson gives 
an exception like this:</p>

<p>hudson.util.IOException2: Failed to join the process
	at hudson.Proc$RemoteProc.join(Proc.java:231)
	at hudson.tasks.Ant.perform(Ant.java:180)
	at hudson.model.Build$RunnerImpl.build(Build.java:138)
	at hudson.model.Build$RunnerImpl.doRun(Build.java:113)
	at hudson.model.AbstractBuild$AbstractRunner.run(AbstractBuild.java:244)
	at hudson.model.Run.run(Run.java:842)
	at hudson.model.Build.run(Build.java:88)
	at hudson.model.ResourceController.execute(ResourceController.java:70)
	at hudson.model.Executor.run(Executor.java:90)
Caused by: java.util.concurrent.ExecutionException: 
hudson.remoting.RequestAbortedException: java.net.SocketException: Connection 
reset
	at hudson.remoting.Request$1.get(Request.java:165)
	at hudson.remoting.Request$1.get(Request.java:134)
	at hudson.remoting.FutureAdapter.get(FutureAdapter.java:32)
	at hudson.Proc$RemoteProc.join(Proc.java:223)
	... 8 more</p>

<p>This in itself is fine, but it then in turn marks the build as failed.  This 
results in Hudson thinking the changes which occurred for this build were the 
cause for the build.</p>

<p>This causes two problems:</p>

<p>  1. When the build is re-run and then works, Hudson won't list the changes 
which occurred before the broken build as being changes which belong to the new 
build.</p>

<p>  2. If you are running the CI Game plugin, the unlucky soul who committed the 
changes immediately before Hudson broke gets -10.0 points.  IMO in this 
situation the points should be docked against Hudson itself, or some other 
equivalent placeholder player...</p>

<p>On a larger scale, <b>any</b> build which fails due to Hudson itself should not be 
marked as failed for the same reason; this just happens to be the most common 
situation which we encounter in practice.</p></pre>
</details>
</details>
<ul><li><i>environment</i>: <code>Platform: All, OS: All</code></li></ul>

**Comment by jtnord** [comment]
remoting does not mark the build as failed, or have any say in that.  Any change to build status would need to be in Jenkins, so if you still would like to see this as an option please check for / open an issue in jenkinsci/jenkins
